/*
@TargetNode='localhost'
@GeneratedBy=evanj
@GenerationDate=08/03/2022 04:26:27
@GenerationHost=EVANPC
*/

instance of cChocoInstaller as $cChocoInstaller1ref
{
SourceInfo = "D:\\evanj\\Projects\\PowerShell Projects\\PowershellProjects\\DSC\\Configuration\\PackageInstaller\\PackageInstaller.ps1::7::9::cChocoInstaller";
 ResourceID = "[cChocoInstaller]installChoco";
 InstallDir = "C:\\ProgramData\\chocolatey";
 ModuleVersion = "2.5.0.0";
 ModuleName = "cChoco";

 ConfigurationName = "PackageInstaller";

};
instance of cChocoPackageInstall as $cChocoPackageInstall1ref
{
Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\cChoco\\2.5.0.0\\DscResources\\cChocoPackageInstallerSet\\cChocoPackageInstallerSet.schema.psm1::39::9::cChocoPackageInstaller";
 ModuleVersion = "2.5.0.0";
 ResourceID = "[cChocoPackageInstaller]cChocoPackageInstaller_Present_osquery::[cChocoPackageInstallerSet]installPackages";
 Source = "";
 ModuleName = "cChoco";
 Name = "osquery";

DependsOn = {

    "[cChocoInstaller]installChoco"};

 ConfigurationName = "PackageInstaller";

};
instance of cChocoPackageInstall as $cChocoPackageInstall2ref
{
Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\cChoco\\2.5.0.0\\DscResources\\cChocoPackageInstallerSet\\cChocoPackageInstallerSet.schema.psm1::39::9::cChocoPackageInstaller";
 ModuleVersion = "2.5.0.0";
 ResourceID = "[cChocoPackageInstaller]cChocoPackageInstaller_Present_googlechrome::[cChocoPackageInstallerSet]installPackages";
 Source = "";
 ModuleName = "cChoco";
 Name = "googlechrome";

DependsOn = {

    "[cChocoInstaller]installChoco"};

 ConfigurationName = "PackageInstaller";

};
instance of cChocoPackageInstall as $cChocoPackageInstall3ref
{
Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\cChoco\\2.5.0.0\\DscResources\\cChocoPackageInstallerSet\\cChocoPackageInstallerSet.schema.psm1::39::9::cChocoPackageInstaller";
 ModuleVersion = "2.5.0.0";
 ResourceID = "[cChocoPackageInstaller]cChocoPackageInstaller_Present_malwarebytes::[cChocoPackageInstallerSet]installPackages";
 Source = "";
 ModuleName = "cChoco";
 Name = "malwarebytes";

DependsOn = {

    "[cChocoInstaller]installChoco"};

 ConfigurationName = "PackageInstaller";

};
instance of cChocoPackageInstall as $cChocoPackageInstall4ref
{
Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\cChoco\\2.5.0.0\\DscResources\\cChocoPackageInstallerSet\\cChocoPackageInstallerSet.schema.psm1::39::9::cChocoPackageInstaller";
 ModuleVersion = "2.5.0.0";
 ResourceID = "[cChocoPackageInstaller]cChocoPackageInstaller_Present_sysinternals::[cChocoPackageInstallerSet]installPackages";
 Source = "";
 ModuleName = "cChoco";
 Name = "sysinternals";

DependsOn = {

    "[cChocoInstaller]installChoco"};

 ConfigurationName = "PackageInstaller";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";


                        MinimumCompatibleVersion = "1.0.0";


                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};


                        Author="evanj";


                        GenerationDate="08/03/2022 04:26:27";


                        GenerationHost="EVANPC";


                        Name="PackageInstaller";


                    };
