/*
@TargetNode='localhost'
@GeneratedBy=evanj
@GenerationDate=08/03/2022 15:09:39
@GenerationHost=EVANPC
*/

instance of cChocoInstaller as $cChocoInstaller1ref
{
ModuleName = "cChoco";
 InstallDir = "C:\\ProgramData\\chocolatey";
 SourceInfo = "D:\\evanj\\Projects\\PowerShell Projects\\PowershellProjects\\DSC\\Configuration\\PackageInstaller\\57d5a302-c2cd-49ab-a566-d6947a033043.ps1::8::9::cChocoInstaller";
 ResourceID = "[cChocoInstaller]installChoco";
 ModuleVersion = "2.5.0.0";
 ConfigurationName = "PackageInstaller";
};
instance of cChocoPackageInstall as $cChocoPackageInstall1ref
{
Source = "";
 ModuleName = "cChoco";
 ResourceID = "[cChocoPackageInstaller]cChocoPackageInstaller_Present_osquery::[cChocoPackageInstallerSet]installPackages";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\cChoco\\2.5.0.0\\DscResources\\cChocoPackageInstallerSet\\cChocoPackageInstallerSet.schema.psm1::39::9::cChocoPackageInstaller";
 Ensure = "Present";
 Name = "osquery";
 ModuleVersion = "2.5.0.0";

DependsOn = {
    "[cChocoInstaller]installChoco"};
 ConfigurationName = "PackageInstaller";
};
instance of cChocoPackageInstall as $cChocoPackageInstall2ref
{
Source = "";
 ModuleName = "cChoco";
 ResourceID = "[cChocoPackageInstaller]cChocoPackageInstaller_Present_googlechrome::[cChocoPackageInstallerSet]installPackages";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\cChoco\\2.5.0.0\\DscResources\\cChocoPackageInstallerSet\\cChocoPackageInstallerSet.schema.psm1::39::9::cChocoPackageInstaller";
 Ensure = "Present";
 Name = "googlechrome";
 ModuleVersion = "2.5.0.0";

DependsOn = {
    "[cChocoInstaller]installChoco"};
 ConfigurationName = "PackageInstaller";
};
instance of cChocoPackageInstall as $cChocoPackageInstall3ref
{
Source = "";
 ModuleName = "cChoco";
 ResourceID = "[cChocoPackageInstaller]cChocoPackageInstaller_Present_malwarebytes::[cChocoPackageInstallerSet]installPackages";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\cChoco\\2.5.0.0\\DscResources\\cChocoPackageInstallerSet\\cChocoPackageInstallerSet.schema.psm1::39::9::cChocoPackageInstaller";
 Ensure = "Present";
 Name = "malwarebytes";
 ModuleVersion = "2.5.0.0";

DependsOn = {
    "[cChocoInstaller]installChoco"};
 ConfigurationName = "PackageInstaller";
};
instance of cChocoPackageInstall as $cChocoPackageInstall4ref
{
Source = "";
 ModuleName = "cChoco";
 ResourceID = "[cChocoPackageInstaller]cChocoPackageInstaller_Present_sysinternals::[cChocoPackageInstallerSet]installPackages";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\cChoco\\2.5.0.0\\DscResources\\cChocoPackageInstallerSet\\cChocoPackageInstallerSet.schema.psm1::39::9::cChocoPackageInstaller";
 Ensure = "Present";
 Name = "sysinternals";
 ModuleVersion = "2.5.0.0";

DependsOn = {
    "[cChocoInstaller]installChoco"};
 ConfigurationName = "PackageInstaller";
};
instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
State = "Running";
 Path = "C:\\Program Files\\osquery\\osqueryd\\osqueryd.exe";
 ModuleName = "PsDesiredStateConfiguration";
 ResourceID = "[Service]osqueryd";
 SourceInfo = "D:\\evanj\\Projects\\PowerShell Projects\\PowershellProjects\\DSC\\Configuration\\PackageInstaller\\57d5a302-c2cd-49ab-a566-d6947a033043.ps1::25::9::Service";
 Description = "osquery daemon service";
 Ensure = "Present";
 BuiltInAccount = "LocalSystem";
 Name = "osqueryd";
 StartupType = "Automatic";

ModuleVersion = "1.0";
DependsOn = {
    "[cChocoPackageInstaller]cChocoPackageInstaller_Present_osquery::[cChocoPackageInstallerSet]installPackages",
     "[cChocoPackageInstaller]cChocoPackageInstaller_Present_googlechrome::[cChocoPackageInstallerSet]installPackages",
     "[cChocoPackageInstaller]cChocoPackageInstaller_Present_malwarebytes::[cChocoPackageInstallerSet]installPackages",
     "[cChocoPackageInstaller]cChocoPackageInstaller_Present_sysinternals::[cChocoPackageInstallerSet]installPackages"};
 ConfigurationName = "PackageInstaller";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="evanj";

                        GenerationDate="08/03/2022 15:09:39";

                        GenerationHost="EVANPC";

                        Name="PackageInstaller";

                    };
