/*
@TargetNode='localhost'
@GeneratedBy=evanj
@GenerationDate=08/01/2022 19:44:40
@GenerationHost=EVANPC
*/

instance of cChocoInstaller as $cChocoInstaller1ref
{
ModuleName = "cChoco";
 InstallDir = "C:\\ProgramData\\chocolatey";
 ResourceID = "[cChocoInstaller]installChoco";
 SourceInfo = "D:\\evanj\\Projects\\PowerShell Projects\\PowershellProjects\\DSC\\Configuration\\PackageInstaller\\PackageInstaller.ps1::7::9::cChocoInstaller";
 ModuleVersion = "2.5.0.0";

 ConfigurationName = "PackageInstaller";

};
instance of cChocoPackageInstall as $cChocoPackageInstall1ref
{
ModuleName = "cChoco";
 Name = "osquery";
 ResourceID = "[cChocoPackageInstaller]installOSQuery";
 SourceInfo = "D:\\evanj\\Projects\\PowerShell Projects\\PowershellProjects\\DSC\\Configuration\\PackageInstaller\\PackageInstaller.ps1::12::9::cChocoPackageInstaller";
 ModuleVersion = "2.5.0.0";

DependsOn = {

    "[cChocoInstaller]installChoco"};

 ConfigurationName = "PackageInstaller";

};
instance of cChocoPackageInstall as $cChocoPackageInstall2ref
{
ModuleName = "cChoco";
 Name = "googlechrome";
 ResourceID = "[cChocoPackageInstaller]installChrome";
 SourceInfo = "D:\\evanj\\Projects\\PowerShell Projects\\PowershellProjects\\DSC\\Configuration\\PackageInstaller\\PackageInstaller.ps1::18::9::cChocoPackageInstaller";
 ModuleVersion = "2.5.0.0";

DependsOn = {

    "[cChocoInstaller]installChoco"};

 ConfigurationName = "PackageInstaller";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";


                        MinimumCompatibleVersion = "1.0.0";


                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};


                        Author="evanj";


                        GenerationDate="08/01/2022 19:44:40";


                        GenerationHost="EVANPC";


                        Name="PackageInstaller";


                    };
